### ISSUE TITLE
Handle exception with proper error message for invalid/unsupported data formats

### ISSUE THREAD

**Issue by navinrathore** [zinggAI/zingg#162]
**Describe the bug**

When invalid data format is given, it results in an exception with no message.
```
022-03-04 07:27:55,265 [main] WARN  org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry - The function round replaced a previously registered function.
 2022-03-04 07:27:55,265 [main] INFO  zingg.ZinggBase - Start reading internal configurations and functions
 2022-03-04 07:27:55,287 [main] INFO  zingg.ZinggBase - Finished reading internal configurations and functions
 java.lang.NullPointerException
        at zingg.util.PipeUtil.getReader(PipeUtil.java:59)
        at zingg.util.PipeUtil.readInternal(PipeUtil.java:87)
        at zingg.util.PipeUtil.readInternal(PipeUtil.java:131)
        at zingg.util.PipeUtil.read(PipeUtil.java:154)
        at zingg.TrainingDataFinder.execute(TrainingDataFinder.java:52)
        at zingg.client.Client.execute(Client.java:211)
        at zingg.client.Client.main(Client.java:154)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2022-03-04 07:27:56,179 [main] WARN  zingg.client.util.Email - Unable to send email Can't send command to SMTP host
 2022-03-04 07:27:56,180 [main] WARN  zingg.client.Client - Apologies for this message. Zingg has encountered an error. null
```

**Expected behavior**

it should handle exception with proper message
 

https://zinggai.slack.com/archives/C02FJ1KAFPD/p1646380473107629?thread_ts=1646380318.202409&cid=C02FJ1KAFPD

**Comment by edmondo1984** [comment]
See as a first fix #178
