### ISSUE TITLE
Issue running models when new Zingg jar is compiled

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#285]
py4j.protocol.Py4JJavaError: An error occurred while calling o148.execute.
: zingg.client.ZinggClientException: zingg.client.FieldDefinition; local class incompatible: stream classdesc serialVersionUID = -2785755064886098506, local class serialVersionUID = 607273313522895964
        at zingg.Matcher.execute(Matcher.java:159)
        at zingg.client.Client.execute(Client.java:215)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vikasgupta78** [comment]
As discussed with Sonal , current not able to reproduce. So on hold for now.

**Comment by vikasgupta78** [comment]
commit 5e6b1fb5 ,  added serialVersionUID in FieldDefinition

**Comment by vikasgupta78** [comment]
issue was reproduced when model in example was generated using a FieldDefinition class without  serialVersionUID

All example models now regenerated

pull request #559
