### ISSUE TITLE
Add support for Delta Lake formatted source data

### ISSUE THREAD

**Issue by lsbilbro** [zinggAI/zingg#360]

**Comment by sonalgoyal** [comment]
when we tested on databricks today with the delta format, we got a npe - believe this is related to #309 

java.lang.NullPointerException
	at zingg.util.PipeUtil.getReader(PipeUtil.java:59)
	at zingg.util.PipeUtil.readInternal(PipeUtil.java:87)
	at zingg.util.PipeUtil.readInternal(PipeUtil.java:131)
	at zingg.util.PipeUtil.read(PipeUtil.java:154)
	at zingg.TrainingDataFinder.execute(TrainingDataFinder.java:52)
	at zingg.client.Client.execute(Client.java:215)
	at zingg.client.Client.main(Client.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by navinrathore** [comment]
* PR #370 shall take care of this issue.
* Similar issue -  #162
