### ISSUE TITLE
Float and long not supported data types

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#490]
getting following null pointer when calling Model with a field which is of type Long

java.lang.NullPointerException
	at zingg.feature.FeatureFactory.get(FeatureFactory.java:23)
	at zingg.util.ModelUtil.loadFeatures(ModelUtil.java:35)
	at zingg.util.ModelUtil.getFeaturers(ModelUtil.java:52)
	at zingg.snowpark.util.SnowModelUtil.getModel(SnowModelUtil.java:37)
	at zingg.snowpark.model.TestSnowModel.testConstructor(TestSnowModel.java:85)

**Comment by vikasgupta78** [comment]
issue fixed via commit d7ab150 and pull request #537 in spark. Separate issue https://github.com/zinggAI/zingg_snowflake/issues/8 logged for snowflake.
