### ISSUE TITLE
assess model is broken post the package changes

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#513]
./scripts/zingg.sh --phase assessModel --conf examples/febrl/config.json
 
java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at zingg.spark.core.executor.SparkZFactory.get(SparkZFactory.java:39)
	at zingg.common.client.Client.setZingg(Client.java:58)
	at zingg.common.client.Client.<init>(Client.java:43)
	at zingg.spark.client.SparkClient.<init>(SparkClient.java:22)
	at zingg.spark.client.SparkClient.getClient(SparkClient.java:46)
	at zingg.common.client.Client.mainMethod(Client.java:173)
	at zingg.spark.client.SparkClient.main(SparkClient.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by sonalgoyal** [comment]
can you please verify this @vikasgupta78 ?

**Comment by vikasgupta78** [comment]
/scripts/zingg.sh --phase assessModel --conf examples/febrl/config.json

INFO:zingg.assessModel:
INFO:zingg.assessModel:No. of Records Marked : 76
INFO:zingg.assessModel:No. of Records Unmarked : 0
INFO:zingg.assessModel:No. of Matches : 14
INFO:zingg.assessModel:No. of Non-Matches : 24
INFO:zingg.assessModel:No. of Not Sure : 0
INFO:zingg.assessModel:
INFO:zingg.assessModel:Phase AssessModel ends

Seems to be working fine
