### ISSUE TITLE
confusing stacktrace while giving python phases

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#520]
this is a debug messageand should be printed as it will confuse the user
java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at zingg.spark.core.executor.SparkZFactory.get(SparkZFactory.java:40)
	at zingg.common.client.Client.setZingg(Client.java:58)
	at zingg.common.client.Client.<init>(Client.java:43)
	at zingg.spark.client.SparkClient.<init>(SparkClient.java:22)
	at zingg.spark.client.SparkClient.getClient(SparkClient.java:47)
	at zingg.common.client.Client.mainMethod(Client.java:173)
	at zingg.spark.client.SparkClient.main(SparkClient.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by sonalgoyal** [comment]
make sure this stack trace is not getting printed in >=INFO logger mode.
