### ISSUE TITLE
link phase not working

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#558]
link phase giving error

./scripts/zingg.sh --phase  link --conf examples/amazon-google/config.json

 2023-03-31 17:30:55,864 [main] INFO  zingg.spark.core.model.SparkModel - threshold while predicting is 0.5
 2023-03-31 17:30:56,240 [main] DEBUG zingg.spark.core.similarity.SparkTransformer - transforming dataset for VectorValueExtractor
 2023-03-31 17:30:56,370 [main] DEBUG zingg.common.core.executor.Matcher - Found dupes 0
 org.apache.spark.sql.AnalysisException: Reference 'z_cluster' is ambiguous, could be: z_cluster, z_cluster.
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.resolve(package.scala:363)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolve(LogicalPlan.scala:122)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveQuoted(LogicalPlan.scala:133)
	at org.apache.spark.sql.Dataset.resolve(Dataset.scala:262)
	at org.apache.spark.sql.Dataset.col(Dataset.scala:1359)
	at zingg.spark.client.SparkFrame.col(SparkFrame.java:110)
	at zingg.spark.client.SparkFrame.col(SparkFrame.java:18)
	at zingg.common.core.util.DSUtil.alignLinked(DSUtil.java:123)
	at zingg.common.core.executor.Linker.writeOutput(Linker.java:44)
	at zingg.common.core.executor.Matcher.execute(Matcher.java:140)
	at zingg.common.client.Client.execute(Client.java:243)
	at zingg.common.client.Client.mainMethod(Client.java:182)
	at zingg.spark.client.SparkClient.main(SparkClient.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by vikasgupta78** [comment]
fixed in commit 6bcbb433 pull request #562
