### ISSUE TITLE
Having trouble saving matched results

### ISSUE THREAD

**Issue by jcm706** [zinggAI/zingg#592]
I have run the `match` phase on a trained model but am not getting any results. I've tried this with both `delta` table output and `parquet` file outputs, swapping from `path` to `location` between these, but in both cases, nothing is being written out. There is no error coming out that would indicate a programmatic failure, so I'm having trouble diagnosing the problem; any assistance you can provide woudl be appreciated!

Versions:
- Zingg version 0.3.4
- DBR 10.4 LTS
- Spark 3.2.1
- Scala 2.12

args:
```
{'output': [{'name': 'entres_tbl_individual_output',
   'format': 'parquet',
   'props': {'location': '/zinggmodels/ent_res_individual/parquet_files/'},
   'id': 0}],
 'data': [{'name': 'entres_tbl_individual_input',
   'format': 'delta',
   'props': {'path': 'dbfs:/user/hive/warehouse/ent_res.db/entres_tbl_individual_input'},
   'id': 0}],
 'zinggDir': '/zinggmodels/ent_res_individual',
 'fieldDefinition': [{redacted}],
 'numPartitions': 200,
 'labelDataSampleSize': 0.0008,
 'modelId': 'entres_individual_model',
 'jobId': 1,
 'collectMetrics': True,
 'showConcise': False,
 'stopWordsCutoff': 0.1,
 'blockSize': 100}
```

**Comment by sonalgoyal** [comment]
What do the logs say @jcm706 ? The last few lines of the match job detail the pipe where the output is being written. Can you please check and let us know what you see there?

**Comment by jcm706** [comment]
I may need some assistance locating the logs. I am using Zingg via the Python API in databricks, and don't see a log file that's intuitively named. Is there a method of the API I can use to view the logs, or is it written to the DBFS?

From the directory containing the model, the file paths I see are:

model
____ block
________ zingg.block
____________ _committed_<numbers>
____________ _committed_<numbers>
____________ _committed_<numbers>
____________ _committed_<numbers>
____________ _started_<numbers>
____________ _part-00000-tid-<numbers>
____ classifier
________ best.model
____________ bestModel
________________ metadata
____________________ _SUCCESS
____________________ part-00000
________________ stages
____________________ 0_vecAssembler_<hexidecimal number>
________________________ metadata
____________________________ _SUCCESS
____________________________ part-00000
____________________ 1_poly_<hex>
________________________ metadata
____________________________ _SUCCESS
____________________________ part-00000
____________________ 2_logreg_<hex>
________________________ data
____________________________ _committed_<numbers>
____________________________ _started_<numbers>
____________________________ _SUCCESS
____________________________ part-00000
________________________ metadata
____________________________ _SUCCESS
____________________________ part-00000

With the following 2 replicating the results under best.model
____________ estimator
____________ evaluator

And 
____________metadata
________________ _SUCCESS
________________ part-00000

And the training data directories of parquet files. 
trainingData
____marked
________parquet files
____unmarked
________parquet files

**Comment by sonalgoyal** [comment]
Logs are available on the cluster you use for running the Zingg program

**Comment by sonalgoyal** [comment]
Thanks, keep me posted! In case I wasn’t clear earlier, I am referring to the driver and worker logs as mentioned at https://docs.databricks.com/clusters/clusters-manage.html#:~:text=View%20cluster%20logs,you%20can%20use%20for%20debugging.

**Comment by jcm706** [comment]
Hi Sonal, it seems I am getting a failed query during execution: 

```
model_details = global_script_vars('ent_res_ind...

org.apache.spark.sql.Dataset.count(Dataset.scala:3209)
org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:311)
org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:158)
zingg.util.GraphUtil.buildGraph(GraphUtil.java:44)
zingg.Matcher.writeOutput(Matcher.java:178)
zingg.Matcher.execute(Matcher.java:155)
zingg.client.Client.execute(Client.java:242)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
py4j.Gateway.invoke(Gateway.java:295)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
py4j.GatewayConnection.run(GatewayConnection.java:251)
java.lang.Thread.run(Thread.java:750)
```

When I look at the Spark UI -> SQL log for the job, I see a failed query, with this explanation:
```
== Photon Explanation ==
Photon does not fully support the query because:
	Unsupported node: InMemoryTableScan
reference node:
	InMemoryTableScan
```

**Comment by sonalgoyal** [comment]
oh. Which version of Spark are you on?

**Comment by sonalgoyal** [comment]
> oh. Which version of Spark are you on?

and whats the size of data you are running along with cluster size information

**Comment by sonalgoyal** [comment]
have you been able to run smaller datasets on same DBR/Spark/Zingg versions? The logs indicate that the photon acceleration is causing some trouble. is it possible to switch that off and try again?

**Comment by jcm706** [comment]
Hi Sonal, clarifying this a bit more, we ran with it turned off, and received a new error:
```
 Caused by: java.lang.NullPointerException
	at zingg.similarity.function.DateSimilarityFunction.call(DateSimilarityFunction.java:20)
	at zingg.similarity.function.DateSimilarityFunction.call(DateSimilarityFunction.java:8)
	at org.apache.spark.sql.UDFRegistration.$anonfun$register$354(UDFRegistration.scala:778)
	... 72 more
```

The only date column is a DOB field in format "YYYY-MM-DD". This didn't affect training, but in creating matches it seems to cause a failure. However, if I define this field as a String in fieldDefinitions, I get an earlier error, during training. I also get an error if I try to enforce string typing in Databricks on the dataframe where I provide labels for candidate pairs. 

```
zingg.client.ZinggClientException: Union can only be performed on tables with the compatible column types. The 6th column of the second table is date type which is not compatible with string at same column of first table;
'Union false, false
```

Since I'm getting an error by defining it as a string or a date, I'm not sure how to use this field and still apply Zingg to this dataset.

**Comment by sonalgoyal** [comment]
Is some of the data in the date column null or empty? I was looking at the code and we are not handling nulls in dates, so It is likely failing there. One option could be to remove such rows, other would be to clean it up.  That may also explain why train with date is working - possibly all the data is non null? Please check your data and let me know.

To make a column string when you already have existing training data as dates would not work. Thus you are getting the union error. You could rebuild the model with the string column type, which means doing the findTrainingData and train steps again. We have some utilities to convert this in the enterprise version, but not in oss. 

Hopefully, the first option of null checking would work for you?

**Comment by jcm706** [comment]
Hi Sonal, 

It looks like I did have a single null value. I've removed it, but am still not getting output. This is the DBR server log for the failed task: 

Failed Stage Scription:
```
org.apache.spark.rdd.RDD.first(RDD.scala:1475)
org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:365)
org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:158)
```

Failure Reason:
```
Job aborted due to stage failure: Task 0 in stage 11344.0 failed 4 times, most recent failure: Lost task 0.3 in stage 11344.0 (TID 110765) (10.40.0.71 executor 111): java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1750)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1280)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2119)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1657)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$2(ResultTask.scala:65)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:65)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:832)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:835)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:690)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodException: org.graphframes.lib.ConnectedComponents$.$deserializeLambda$(java.lang.invoke.SerializedLambda)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at java.lang.invoke.SerializedLambda$1.run(SerializedLambda.java:224)
	at java.lang.invoke.SerializedLambda$1.run(SerializedLambda.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:221)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1274)
	... 38 more

Driver stacktrace:
```

**Comment by sonalgoyal** [comment]
:-( 

have you been able to run smaller datasets on same DBR/Spark/Zingg versions?

**Comment by sonalgoyal** [comment]
Thanks for the information. This behaviour is strange. The NoSuchMethodException is generally an indicator of the versions and should not be thrown merely on higher volumes. Can you please try the following:
1. Use same cluster but a different model (like Zingg feblr example)
2. Can you please check with your Databricks support which version of graphframes they have on the given DBR version? Zingg is built with 0.8.1-spark3.0-s_2.12, I suspect there may be a version issue here.

**Comment by sonalgoyal** [comment]
glad it worked @jcm706 , please keep us posted if and when this resurfaces or if you need any other help!
