### ISSUE TITLE
issue in date similarity with null values

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#611]
Hi <@U02F39UQM2B>,
I am encountering this error during the matching stage. The data source is MongoDB. Please help me to solve this error.

[Slack Message](https://zinggai.slack.com/archives/C02G7L755KJ/p1686550804081859?thread_ts=1685341103.056149&cid=C02G7L755KJ)

**Comment by vikasgupta78** [comment]
1.  date format for csv file in spark is yyyy-mm-dd
2. If given without hyphens read as null
3. attached the test.csv used in testing and corresponding input data from logs
(dob as date in config.json both at field definition and schema ddl definition)
5. Error was reproduced in train phase:

Caused by: java.lang.NullPointerException
	at zingg.common.core.similarity.function.DateSimilarityFunction.call(DateSimilarityFunction.java:20)
	at zingg.common.core.similarity.function.DateSimilarityFunction.call(DateSimilarityFunction.java:8)
	at zingg.spark.core.similarity.SparkSimFunction.call(SparkSimFunction.java:21)
	at zingg.spark.core.similarity.SparkSimFunction.call(SparkSimFunction.java:7)
	at org.apache.spark.sql.UDFRegistration.$anonfun$register$354(UDFRegistration.scala:793)
[test.csv](https://github.com/zinggAI/zingg/files/11767581/test.csv)

[INP-DATA.log](https://github.com/zinggAI/zingg/files/11767595/INP-DATA.log)
