### ISSUE TITLE
using ZinggWithSpark in python causes error

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#640]
In examples/febrl/FebrlExample.py

if we use zingg = ZinggWithSpark(args, options) instead of zingg = Zingg(args, options)

./scripts/zingg.sh --run examples/febrl/FebrlExample.py

Got following error:

py4j.protocol.Py4JError: An error occurred while calling None.zingg.spark.client.SparkClient. Trace:
py4j.Py4JException: Constructor zingg.spark.client.SparkClient([class zingg.common.client.Arguments, class zingg.common.client.ClientOptions, class org.apache.spark.sql.SparkSession]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
	at py4j.Gateway.invoke(Gateway.java:237)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

**Comment by vikasgupta78** [comment]
fixed in commit 4fd68f9c by adding extra constructor to SparkClient

**Comment by vikasgupta78** [comment]
PR #641 raised
