### ISSUE TITLE
zingg client option initialization error in ENTERPRISE branch

### ISSUE THREAD

**Issue by gnanaprakash-ravi** [zinggAI/zingg#666]
**Describe the bug**
While testing scripts in the Zingg enterprise branch, an error is option initialization
 2023-09-07 10:48:08,975 [main] WARN  zingg.common.client.Client - Apologies for this message. Zingg has encountered an error. null
 java.lang.ExceptionInInitializerError
        at zingg.common.client.ClientOptions.<clinit>(ClientOptions.java:56)

**To Reproduce**
1. mvn clean compile package -Dspark=3.2 -Dmaven.test.skip=true
2. ./scripts/zingg.sh --phase findTrainingData --conf examples/febrl/config.json --zinggDir /tmp/z_test

**Screenshots**
[image](https://github.com/zinggAI/zingg/assets/89972506/db783d02-b7ef-4023-9453-a1bc5dd26638)

**Comment by sonalgoyal** [comment]
the context was not getting initialized, fixed in 9033c033

**Comment by gnanaprakash-ravi** [comment]
The first 3 phases ran successfully, in the "match" phase NullPointerException error occurred.

:~/zingg$ ./scripts/zingg.sh --phase match --conf examples/febrl/config.json --zinggDir /tmp/z_test
2023-09-08 22:48:33,523 [main] WARN  org.apache.spark.util.Utils - Your hostname, LAPTOP-51G8JQDT resolves to a loopback address: 127.0.1.1; using 172.21.38.234 instead (on interface eth0)
 2023-09-08 22:48:33,524 [main] WARN  org.apache.spark.util.Utils - Set SPARK_LOCAL_IP if you need to bind to another address
 2023-09-08 22:48:34,991 [main] WARN  org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
 2023-09-08 22:48:35,176 [main] INFO  zingg.common.client.Client -
 2023-09-08 22:48:35,176 [main] INFO  zingg.common.client.Client - ********************************************************
 2023-09-08 22:48:35,176 [main] INFO  zingg.common.client.Client - *                    Zingg AI                          *
 2023-09-08 22:48:35,176 [main] INFO  zingg.common.client.Client - *               (C) 2021 Zingg.AI                      *
 2023-09-08 22:48:35,176 [main] INFO  zingg.common.client.Client - ********************************************************
 2023-09-08 22:48:35,177 [main] INFO  zingg.common.client.Client -
 2023-09-08 22:48:35,177 [main] INFO  zingg.common.client.Client - using: Zingg v0.4.0
 2023-09-08 22:48:35,177 [main] INFO  zingg.common.client.Client -
 2023-09-08 22:48:35,178 [main] INFO  zingg.common.client.ClientOptions - --phase
 2023-09-08 22:48:35,178 [main] INFO  zingg.common.client.ClientOptions - match
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - --conf
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - examples/febrl/config.json
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - --zinggDir
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - /tmp/z_test
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - --email
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - zingg@zingg.ai
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - --license
 2023-09-08 22:48:35,179 [main] INFO  zingg.common.client.ClientOptions - zinggLicense.txt
 2023-09-08 22:48:35,285 [main] WARN  zingg.common.client.Arguments - Config Argument is examples/febrl/config.json
 2023-09-08 22:48:35,370 [main] WARN  zingg.common.client.Arguments - phase is match
 2023-09-08 22:48:35,370 [main] INFO  zingg.common.client.Client - Using zingg dir from command line
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client -
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - **************************************************************************
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - *            ** Note about analytics collection by Zingg AI **           *
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - *                                                                        *
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - *  Please note that Zingg captures a few metrics about application's     *
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - *  runtime parameters. However, no user's personal data or application   *
 2023-09-08 22:48:35,371 [main] INFO  zingg.common.client.Client - *  data is captured. If you want to switch off this feature, please      *
 2023-09-08 22:48:35,372 [main] INFO  zingg.common.client.Client - *  set the flag collectMetrics to false in config. For details, please   *
 2023-09-08 22:48:35,372 [main] INFO  zingg.common.client.Client - *  refer to the Zingg docs (https://docs.zingg.ai/docs/security.html)    *
 2023-09-08 22:48:35,372 [main] INFO  zingg.common.client.Client - **************************************************************************
 2023-09-08 22:48:35,372 [main] INFO  zingg.common.client.Client -
 java.lang.NullPointerException
        at zingg.common.core.executor.Matcher.getTestData(Matcher.java:32)
        at zingg.common.core.executor.Matcher.execute(Matcher.java:93)
        at zingg.common.client.Client.execute(Client.java:265)
        at zingg.common.client.Client.mainMethod(Client.java:205)
        at zingg.spark.client.SparkClient.main(SparkClient.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2023-09-08 22:48:37,299 [main] WARN  zingg.common.client.util.Email - Unable to send email Can't send command to SMTP host
 2023-09-08 22:48:37,299 [main] WARN  zingg.common.client.Client - Apologies for this message. Zingg has encountered an error. null
 zingg.common.client.ZinggClientException
        at zingg.common.core.executor.Matcher.execute(Matcher.java:172)
        at zingg.common.client.Client.execute(Client.java:265)
        at zingg.common.client.Client.mainMethod(Client.java:205)
        at zingg.spark.client.SparkClient.main(SparkClient.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
