### ISSUE TITLE
zingg NullPointerException error in ENTERPRISE branch while running "match" phase

### ISSUE THREAD

**Issue by gnanaprakash-ravi** [zinggAI/zingg#668]
After this fix [9033c03](https://github.com/zinggAI/zingg/commit/9033c033388515e6489c64949f58d70a5347dbbb) ,

The first 3 phases ran successfully, in the "match" phase NullPointerException error occurred.

:~/zingg$ ./scripts/zingg.sh --phase match --conf examples/febrl/config.json --zinggDir /tmp/z_test
2023-09-08 22:48:33,523 [main] WARN org.apache.spark.util.Utils - Your hostname, LAPTOP-51G8JQDT resolves to a loopback address: 127.0.1.1; using 172.21.38.234 instead (on interface eth0)
2023-09-08 22:48:33,524 [main] WARN org.apache.spark.util.Utils - Set SPARK_LOCAL_IP if you need to bind to another address
2023-09-08 22:48:34,991 [main] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-09-08 22:48:35,176 [main] INFO zingg.common.client.Client -
2023-09-08 22:48:35,176 [main] INFO zingg.common.client.Client - ********************************************************
2023-09-08 22:48:35,176 [main] INFO zingg.common.client.Client - * Zingg AI *
2023-09-08 22:48:35,176 [main] INFO zingg.common.client.Client - * (C) 2021 Zingg.AI *
2023-09-08 22:48:35,176 [main] INFO zingg.common.client.Client - ********************************************************
2023-09-08 22:48:35,177 [main] INFO zingg.common.client.Client -
2023-09-08 22:48:35,177 [main] INFO zingg.common.client.Client - using: Zingg v0.4.0
2023-09-08 22:48:35,177 [main] INFO zingg.common.client.Client -
2023-09-08 22:48:35,178 [main] INFO zingg.common.client.ClientOptions - --phase
2023-09-08 22:48:35,178 [main] INFO zingg.common.client.ClientOptions - match
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - --conf
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - examples/febrl/config.json
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - --zinggDir
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - /tmp/z_test
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - --email
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - [zingg@zingg.ai](mailto:zingg@zingg.ai)
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - --license
2023-09-08 22:48:35,179 [main] INFO zingg.common.client.ClientOptions - zinggLicense.txt
2023-09-08 22:48:35,285 [main] WARN zingg.common.client.Arguments - Config Argument is examples/febrl/config.json
2023-09-08 22:48:35,370 [main] WARN zingg.common.client.Arguments - phase is match
2023-09-08 22:48:35,370 [main] INFO zingg.common.client.Client - Using zingg dir from command line
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client -
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - **************************************************************************
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - * ** Note about analytics collection by Zingg AI ** *
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - * *
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - * Please note that Zingg captures a few metrics about application's *
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - * runtime parameters. However, no user's personal data or application *
2023-09-08 22:48:35,371 [main] INFO zingg.common.client.Client - * data is captured. If you want to switch off this feature, please *
2023-09-08 22:48:35,372 [main] INFO zingg.common.client.Client - * set the flag collectMetrics to false in config. For details, please *
2023-09-08 22:48:35,372 [main] INFO zingg.common.client.Client - * refer to the Zingg docs (https://docs.zingg.ai/docs/security.html) *
2023-09-08 22:48:35,372 [main] INFO zingg.common.client.Client - **************************************************************************
2023-09-08 22:48:35,372 [main] INFO zingg.common.client.Client -
java.lang.NullPointerException
at zingg.common.core.executor.Matcher.getTestData(Matcher.java:32)
at zingg.common.core.executor.Matcher.execute(Matcher.java:93)
at zingg.common.client.Client.execute(Client.java:265)
at zingg.common.client.Client.mainMethod(Client.java:205)
at zingg.spark.client.SparkClient.main(SparkClient.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2023-09-08 22:48:37,299 [main] WARN zingg.common.client.util.Email - Unable to send email Can't send command to SMTP host
2023-09-08 22:48:37,299 [main] WARN zingg.common.client.Client - Apologies for this message. Zingg has encountered an error. null
zingg.common.client.ZinggClientException
at zingg.common.core.executor.Matcher.execute(Matcher.java:172)
at zingg.common.client.Client.execute(Client.java:265)
at zingg.common.client.Client.mainMethod(Client.java:205)
at zingg.spark.client.SparkClient.main(SparkClient.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sonalgoyal** [comment]
fixed through 342571995320779abe988816eb56693e09af7ad4 

@gnanaprakash-ravi  please verify

**Comment by gnanaprakash-ravi** [comment]
All the examples ran successfully in 4 phases, 
when running ncVoters5M examples, outOfMemoryError occurred

(base) r_gnanaprakash@LAPTOP-51G8JQDT:~/zingg$ ./scripts/zingg.sh --phase findTrainingData --conf examples/ncVoters5M/config.json --zinggDir /tmp/z_test
2023-09-09 23:58:01,598 [main] WARN  org.apache.spark.util.Utils - Your hostname, LAPTOP-51G8JQDT resolves to a loopback address: 127.0.1.1; using 172.30.44.49 instead (on interface eth0)
 2023-09-09 23:58:01,599 [main] WARN  org.apache.spark.util.Utils - Set SPARK_LOCAL_IP if you need to bind to another address
 2023-09-09 23:58:03,101 [main] WARN  org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
 2023-09-09 23:58:03,276 [main] INFO  zingg.common.client.Client -
 2023-09-09 23:58:03,276 [main] INFO  zingg.common.client.Client - ********************************************************
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client - *                    Zingg AI                          *
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client - *               (C) 2021 Zingg.AI                      *
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client - ********************************************************
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client -
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client - using: Zingg v0.4.0
 2023-09-09 23:58:03,277 [main] INFO  zingg.common.client.Client -
 2023-09-09 23:58:03,278 [main] INFO  zingg.common.client.ClientOptions - --phase
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - findTrainingData
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - --conf
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - examples/ncVoters5M/config.json
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - --zinggDir
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - /tmp/z_test
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - --email
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - zingg@zingg.ai
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - --license
 2023-09-09 23:58:03,279 [main] INFO  zingg.common.client.ClientOptions - zinggLicense.txt
 2023-09-09 23:58:03,431 [main] WARN  zingg.common.client.Arguments - Config Argument is examples/ncVoters5M/config.json
 2023-09-09 23:58:03,509 [main] WARN  zingg.common.client.Arguments - phase is findTrainingData
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - Using zingg dir from command line
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client -
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - **************************************************************************
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - *            ** Note about analytics collection by Zingg AI **           *
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - *                                                                        *
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - *  Please note that Zingg captures a few metrics about application's     *
 2023-09-09 23:58:03,509 [main] INFO  zingg.common.client.Client - *  runtime parameters. However, no user's personal data or application   *
 2023-09-09 23:58:03,510 [main] INFO  zingg.common.client.Client - *  data is captured. If you want to switch off this feature, please      *
 2023-09-09 23:58:03,510 [main] INFO  zingg.common.client.Client - *  set the flag collectMetrics to false in config. For details, please   *
 2023-09-09 23:58:03,510 [main] INFO  zingg.common.client.Client - *  refer to the Zingg docs (https://docs.zingg.ai/docs/security.html)    *
 2023-09-09 23:58:03,510 [main] INFO  zingg.common.client.Client - **************************************************************************
 2023-09-09 23:58:03,510 [main] INFO  zingg.common.client.Client -
 2023-09-09 23:58:04,368 [main] WARN  org.apache.spark.util.Utils - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
 2023-09-09 23:58:05,624 [main] WARN  zingg.common.core.util.PipeUtil - Reading Pipe [name=test, format=csv, preprocessors=null, props={location=examples/ncVoters5M/5Party-ocp20/, delimiter=,, header=false}]
 2023-09-09 23:58:27,911 [main] WARN  zingg.common.core.executor.TrainingDataFinder - Read input data 5000005
 2023-09-09 23:58:27,912 [main] WARN  zingg.common.core.executor.TrainingDataFinder - input data schema is StructType(StructField(z_zid,LongType,false), StructField(recid,StringType,true), StructField(givenname,StringType,true), StructField(surname,StringType,true), StructField(suburb,StringType,true), StructField(postcode,StringType,true), StructField(z_zsource,StringType,false))
 2023-09-09 23:58:27,912 [main] WARN  zingg.common.core.util.PipeUtil - Reading Pipe [name=null, format=parquet, preprocessors=null, props={location=/tmp/z_test/104/trainingData//marked/}]
 2023-09-09 23:58:27,941 [main] WARN  zingg.common.core.util.PipeUtil - Path does not exist: file:/tmp/z_test/104/trainingData/marked
 2023-09-09 23:58:27,941 [main] WARN  zingg.common.core.util.DSUtil - No preexisting marked training samples
 2023-09-09 23:58:27,941 [main] WARN  zingg.common.core.util.DSUtil - No training data found
 2023-09-09 23:58:28,056 [main] INFO  zingg.common.core.executor.TrainingDataFinder - Created positive sample pairs
 2023-09-09 23:58:28,179 [main] INFO  zingg.common.core.executor.TrainingDataFinder - Preprocessing DS for stopWords
 2023-09-09 23:58:28,180 [main] WARN  org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry - The function removestopwordsudf replaced a previously registered function.
 2023-09-09 23:58:28,198 [main] WARN  org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry - The function round replaced a previously registered function.
  2023-09-09 23:58:45,300 [main] INFO  zingg.common.core.util.Heuristics - **Block size **100 and total count was 499041
 2023-09-09 23:58:45,301 [main] INFO  zingg.common.core.util.Heuristics - Heuristics suggest 100
 2023-09-09 23:58:45,301 [main] INFO  zingg.common.core.util.BlockingTreeUtil - Learning indexing rules for block size 100
2023-09-09 23:59:43,265 [main] WARN  zingg.common.client.util.Email - Unable to send email Can't send command to SMTP host
 2023-09-09 23:59:43,266 [main] WARN  zingg.common.client.Client - Apologies for this message. Zingg has encountered an error. GC overhead limit exceeded
 java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.spark.unsafe.types.UTF8String.getBytes(UTF8String.java:297)
        at org.apache.spark.unsafe.types.UTF8String.toString(UTF8String.java:1375)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.createExternalRow_0_1$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:181)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:172)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.TraversableLike$$Lambda$18/846947180.apply(Unknown Source)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3715)
        at org.apache.spark.sql.Dataset.$anonfun$collectAsList$1(Dataset.scala:2983)
        at org.apache.spark.sql.Dataset$$Lambda$3898/260296993.apply(Unknown Source)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3706)
        at org.apache.spark.sql.Dataset$$Lambda$1512/137902612.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1520/472766619.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1513/962221884.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3704)
        at org.apache.spark.sql.Dataset.collectAsList(Dataset.scala:2982)
        at zingg.spark.client.SparkFrame.collectAsList(SparkFrame.java:70)
        at zingg.common.core.util.BlockingTreeUtil.createBlockingTree(BlockingTreeUtil.java:60)
        at zingg.common.core.executor.TrainingDataFinder.execute(TrainingDataFinder.java:81)
        at zingg.common.client.Client.execute(Client.java:265)

**Comment by sonalgoyal** [comment]
Ok thanks, we can close this as memory issue can be tackled through settings
