### ISSUE TITLE
UT not working for parseArguments function in client.py

### ISSUE THREAD

**Issue by gnanaprakash-ravi** [zinggAI/zingg#690]
**Describe the bug**
This UT gave a SystemExit error for the parseArguments function in the client.py

`def test_parseArguments(self):
        args = ["--phase", "train",
                "--conf", "conf.json"]

        parsed_args = parseArguments(args)

        self.assertEqual(parsed_args.phase, "train")
        self.assertEqual(parsed_args.conf, "conf.json")`

**To Reproduce**
1. run the command : ~/zingg$ ./scripts/zingg.sh --run test/pythonTest.py

**Expected behavior**
The UT should run.

**Screenshots**
` .
======================================================================
ERROR: test_parseArguments (test.testFebrl.testArgs.ClientTest.test_parseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/r_gnanaprakash/zingg/test/testFebrl/testArgs.py", line 599, in test_parseArguments
    parsed_args = parseArguments(args)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/site-packages/zingg/client.py", line 757, in parseArguments
    args, remaining_args = parser.parse_known_args()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/argparse.py", line 2142, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/argparse.py", line 2630, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/argparse.py", line 2617, in exit
    _sys.exit(status)
SystemExit: 2

----------------------------------------------------------------------
Ran 5 tests in 256.222s

FAILED (errors=1)`

**Comment by vikasgupta78** [comment]
Code change looks alright to me
