### ISSUE TITLE
trainingSamples with z_zid or not

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#708]
LE
  [26 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324164275149?thread_ts=1698236476.059449&cid=C02JNH144TB)
[@Sonal Goyal](https://zinggai.slack.com/team/U02F39UQM2B)
 in the /unmarked directory I can see these additional columns:
'z_zid', 'z_cluster', 'z_prediction', 'z_score', 'z_isMatch'
according to the docs I've added to the trainingSamples only:
'z_cluster', 'z_isMatch'
should I add any other? all other column are same (edited) 

Sonal Goyal
  [22 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324387368429?thread_ts=1698236476.059449&cid=C02JNH144TB)
we do a union by name  internally as far as i remember so it should have worked. yes, please do try with this and let us know how it goes.

LE
  [21 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324450409509?thread_ts=1698236476.059449&cid=C02JNH144TB)
[@Sonal Goyal](https://zinggai.slack.com/team/U02F39UQM2B)
 but which values should I put for:
'z_zid', 'z_prediction', 'z_score'
?

LE
  [20 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324542993139?thread_ts=1698236476.059449&cid=C02JNH144TB)
also 40-38/2 = 1 and not three, seems we should add only one column... (edited) 

Sonal Goyal
  [14 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324875754209?thread_ts=1698236476.059449&cid=C02JNH144TB)
I am actually surprised because we [fixed](https://github.com/zinggAI/zingg/commit/eeed8a44047ef4168bc19d12b33d7d48c9b24344) this a long while ago. z_zid is worth a try. Which release are you on?

LE
  [14 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324893617519?thread_ts=1698236476.059449&cid=C02JNH144TB)
0.3.4

Sonal Goyal
  [13 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698324937582359?thread_ts=1698236476.059449&cid=C02JNH144TB)
ok. 
[@Vikas Gupta](https://zinggai.slack.com/team/U04BTQJ0NG2)
 can you please check this?

Vikas Gupta
  [2 minutes ago](https://zinggai.slack.com/archives/C02JNH144TB/p1698325607159109?thread_ts=1698236476.059449&cid=C02JNH144TB)
sure I will try to reproduce it on my machine and let you know

**Comment by vikasgupta78** [comment]
Tried in 0.4.0 and worked fine.

Following are the findings:

1. z_cluster string, z_isMatch integer are the only cols that need to be added to trainingSamples
2. z_zid is added by dsutil using flag:
ZFrame<D, R, C> trSamples = pipeUtil.read(true, false, args.getTrainingSamples());
here the first param is for adding the z_zid
3. Also dsutil is using unionbyname:
trFile.unionByName(trSamples, true);

will now try in 0.3.4

**Comment by vikasgupta78** [comment]
Issue reproduced in 0.3.4 so looks like it was fixed in 0.4.0:

Steps tried:

1. run findTrainingData
2. run label
3. run findTrainingData :
error comes as this is the stage where training samples provided and data labeled is unionized:

 2023-10-27 20:29:05,168 [main] WARN  zingg.TrainingDataFinder - Read training samples 2 neg 3
 2023-10-27 20:29:05,779 [main] INFO  zingg.TrainingDataFinder - Created positive sample pairs 
 2023-10-27 20:29:05,789 [main] WARN  org.apache.spark.sql.catalyst.util.package - Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
 org.apache.spark.sql.AnalysisException: Union can only be performed on tables with the same number of columns, but the first table has 26 columns and the second table has 24 columns;
'Union false, false
:- Project [z_zid#446L, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779, z_z_zid#796L, z_fname#799, z_lname#800, z_stNo#801, z_add1#802, z_add2#803, z_city#804, z_areacode#805, z_state#806, z_dob#807, z_ssn#808, ... 2 more fields]
:  +- Filter (cast(z_isMatch#780 as int) = 1)
:     +- Filter (z_zid#446L > z_z_zid#796L)
:        +- Join Inner, (z_cluster#447 = z_z_cluster#797)
:           :- Union false, false
:           :  :- Project [z_zid#446L, z_cluster#447, cast(z_isMatch#450 as string) AS z_isMatch#780, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779]
:           :  :  +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, null AS id#779]
:           :  :     +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:           :  :        +- Project [z_zid#446L, z_cluster#447, z_score#449, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:           :  :           +- Relation[z_zid#446L,z_cluster#447,z_prediction#448,z_score#449,z_isMatch#450,fname#451,lname#452,stNo#453,add1#454,add2#455,city#456,areacode#457,state#458,dob#459,ssn#460,z_source#461] parquet
:           :  +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, z_source#778, id#683]
:           :     +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, null AS z_source#778, id#683]
:           :        +- LogicalRDD [z_zid#680L, z_cluster#681, z_isMatch#682, id#683, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693], false
:           +- Project [z_zid#446L AS z_z_zid#796L, z_cluster#447 AS z_z_cluster#797, z_isMatch#780 AS z_z_isMatch#798, fname#451 AS z_fname#799, lname#452 AS z_lname#800, stNo#453 AS z_stNo#801, add1#454 AS z_add1#802, add2#455 AS z_add2#803, city#456 AS z_city#804, areacode#457 AS z_areacode#805, state#458 AS z_state#806, dob#459 AS z_dob#807, ssn#460 AS z_ssn#808, z_source#461 AS z_z_source#809, id#779 AS z_id#810]
:              +- Union false, false
:                 :- Project [z_zid#446L, z_cluster#447, cast(z_isMatch#450 as string) AS z_isMatch#780, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779]
:                 :  +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, null AS id#779]
:                 :     +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:                 :        +- Project [z_zid#446L, z_cluster#447, z_score#449, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:                 :           +- Relation[z_zid#446L,z_cluster#447,z_prediction#448,z_score#449,z_isMatch#450,fname#451,lname#452,stNo#453,add1#454,add2#455,city#456,areacode#457,state#458,dob#459,ssn#460,z_source#461] parquet
:                 +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, z_source#778, id#683]
:                    +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, null AS z_source#778, id#683]
:                       +- LogicalRDD [z_zid#680L, z_cluster#681, z_isMatch#682, id#683, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693], false
+- Join Inner, (z_zid#77L = z_z_zid#4943L)
   :- Project [z_zid#77L, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89]
   :  +- Sample 0.0, 0.5, false, -6595728288792390096
   :     +- LogicalRDD [z_zid#77L, id#78, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89], false
   +- Project [z_zid#77L AS z_z_zid#4943L, fname#79 AS z_fname#4944, lname#80 AS z_lname#4945, stNo#81 AS z_stNo#4946, add1#82 AS z_add1#4947, add2#83 AS z_add2#4948, city#84 AS z_city#4949, areacode#85 AS z_areacode#4950, state#86 AS z_state#4951, dob#87 AS z_dob#4952, ssn#88 AS z_ssn#4953, z_source#89 AS z_z_source#4954]
      +- Project [z_zid#77L, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89]
         +- Sample 0.0, 0.5, false, -6595728288792390096
            +- LogicalRDD [z_zid#77L, id#78, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89], false

	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.failAnalysis(CheckAnalysis.scala:50)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.failAnalysis$(CheckAnalysis.scala:49)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:155)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$21(CheckAnalysis.scala:370)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$21$adapted(CheckAnalysis.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:362)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:93)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:184)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:93)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:90)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:155)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:176)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:228)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:173)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:73)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:73)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:71)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:63)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:88)
	at org.apache.spark.sql.Dataset.withSetOperator(Dataset.scala:3727)
	at org.apache.spark.sql.Dataset.union(Dataset.scala:1993)
	at zingg.TrainingDataFinder.execute(TrainingDataFinder.java:86)
	at zingg.client.Client.execute(Client.java:242)
	at zingg.client.Client.main(Client.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2023-10-27 20:29:07,740 [main] WARN  zingg.client.util.Email - Unable to send email Can't send command to SMTP host
 2023-10-27 20:29:07,741 [main] WARN  zingg.client.Client - Apologies for this message. Zingg has encountered an error. Union can only be performed on tables with the same number of columns, but the first table has 26 columns and the second table has 24 columns;
'Union false, false
:- Project [z_zid#446L, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779, z_z_zid#796L, z_fname#799, z_lname#800, z_stNo#801, z_add1#802, z_add2#803, z_city#804, z_areacode#805, z_state#806, z_dob#807, z_ssn#808, ... 2 more fields]
:  +- Filter (cast(z_isMatch#780 as int) = 1)
:     +- Filter (z_zid#446L > z_z_zid#796L)
:        +- Join Inner, (z_cluster#447 = z_z_cluster#797)
:           :- Union false, false
:           :  :- Project [z_zid#446L, z_cluster#447, cast(z_isMatch#450 as string) AS z_isMatch#780, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779]
:           :  :  +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, null AS id#779]
:           :  :     +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:           :  :        +- Project [z_zid#446L, z_cluster#447, z_score#449, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:           :  :           +- Relation[z_zid#446L,z_cluster#447,z_prediction#448,z_score#449,z_isMatch#450,fname#451,lname#452,stNo#453,add1#454,add2#455,city#456,areacode#457,state#458,dob#459,ssn#460,z_source#461] parquet
:           :  +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, z_source#778, id#683]
:           :     +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, null AS z_source#778, id#683]
:           :        +- LogicalRDD [z_zid#680L, z_cluster#681, z_isMatch#682, id#683, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693], false
:           +- Project [z_zid#446L AS z_z_zid#796L, z_cluster#447 AS z_z_cluster#797, z_isMatch#780 AS z_z_isMatch#798, fname#451 AS z_fname#799, lname#452 AS z_lname#800, stNo#453 AS z_stNo#801, add1#454 AS z_add1#802, add2#455 AS z_add2#803, city#456 AS z_city#804, areacode#457 AS z_areacode#805, state#458 AS z_state#806, dob#459 AS z_dob#807, ssn#460 AS z_ssn#808, z_source#461 AS z_z_source#809, id#779 AS z_id#810]
:              +- Union false, false
:                 :- Project [z_zid#446L, z_cluster#447, cast(z_isMatch#450 as string) AS z_isMatch#780, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, id#779]
:                 :  +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461, null AS id#779]
:                 :     +- Project [z_zid#446L, z_cluster#447, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:                 :        +- Project [z_zid#446L, z_cluster#447, z_score#449, z_isMatch#450, fname#451, lname#452, stNo#453, add1#454, add2#455, city#456, areacode#457, state#458, dob#459, ssn#460, z_source#461]
:                 :           +- Relation[z_zid#446L,z_cluster#447,z_prediction#448,z_score#449,z_isMatch#450,fname#451,lname#452,stNo#453,add1#454,add2#455,city#456,areacode#457,state#458,dob#459,ssn#460,z_source#461] parquet
:                 +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, z_source#778, id#683]
:                    +- Project [z_zid#680L, z_cluster#681, z_isMatch#682, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693, null AS z_source#778, id#683]
:                       +- LogicalRDD [z_zid#680L, z_cluster#681, z_isMatch#682, id#683, fname#684, lname#685, stNo#686, add1#687, add2#688, city#689, areacode#690, state#691, dob#692, ssn#693], false
+- Join Inner, (z_zid#77L = z_z_zid#4943L)
   :- Project [z_zid#77L, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89]
   :  +- Sample 0.0, 0.5, false, -6595728288792390096
   :     +- LogicalRDD [z_zid#77L, id#78, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89], false
   +- Project [z_zid#77L AS z_z_zid#4943L, fname#79 AS z_fname#4944, lname#80 AS z_lname#4945, stNo#81 AS z_stNo#4946, add1#82 AS z_add1#4947, add2#83 AS z_add2#4948, city#84 AS z_city#4949, areacode#85 AS z_areacode#4950, state#86 AS z_state#4951, dob#87 AS z_dob#4952, ssn#88 AS z_ssn#4953, z_source#89 AS z_z_source#4954]
      +- Project [z_zid#77L, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89]
         +- Sample 0.0, 0.5, false, -6595728288792390096
            +- LogicalRDD [z_zid#77L, id#78, fname#79, lname#80, stNo#81, add1#82, add2#83, city#84, areacode#85, state#86, dob#87, ssn#88, z_source#89], false

 %  
[samples.csv](https://github.com/zinggAI/zingg/files/13190286/samples.csv)


[config.json](https://github.com/zinggAI/zingg/files/13190285/config.json)

**Comment by vikasgupta78** [comment]
As @sonalgoyal Sonal suspected we were doing union in 0.3.4, TrainingDataFinder:

posPairs = posPairs.union(posSamples);
