### ISSUE TITLE
generateDocs not working on data bricks

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#740]
options = ClientOptions([ClientOptions.PHASE,"generateDocs"])

#Zingg execution for the given phase
zingg = ZinggWithSpark(args, options)
zingg.initAndExecute()

['--phase', 'generateDocs']
arguments for client options are  ['--phase', 'generateDocs', '--license', 'zinggLic.txt', '--email', 'zingg@zingg.ai', '--conf', 'dummyConf.json']
zingg.common.client.ZinggClientException: java.lang.Long cannot be cast to java.lang.Integer
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
File <command-1824376572372026>:5
      3 #Zingg execution for the given phase
      4 zingg = ZinggWithSpark(args, options)
----> 5 zingg.initAndExecute()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/zingg/client.py:144, in Zingg.initAndExecute(self)
    142         self.client.execute()
    143 else:
--> 144     self.client.execute()

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:

**Comment by vikasgupta78** [comment]
further error trace from driver logs:

java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at zingg.spark.client.SparkFrame.getAsInt(SparkFrame.java:350)
	at zingg.spark.client.SparkFrame.getAsInt(SparkFrame.java:18)
	at zingg.common.core.documenter.ModelDocumenter.putSummaryCounts(ModelDocumenter.java:107)
	at zingg.common.core.documenter.ModelDocumenter.populateTemplateData(ModelDocumenter.java:81)
	at zingg.common.core.documenter.ModelDocumenter.createModelDocument(ModelDocumenter.java:50)
	at zingg.common.core.documenter.ModelDocumenter.process(ModelDocumenter.java:40)
	at zingg.common.core.executor.Documenter.execute(Documenter.java:25)
	at zingg.common.client.Client.execute(Client.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)



The issue seems to be that the column z_isMatch whose values could only be 0,1, 2 is coming as long data type in data bricks

**Comment by vikasgupta78** [comment]
example:

+---------+-----------------+
|z_isMatch|z_pair_wise_count|
+---------+-----------------+
|        0|               24|
|        1|               16|
+---------+-----------------+

**Comment by vikasgupta78** [comment]
spark.read.parquet(MARKED_DIR).schema

ut[21]: StructType([StructField('z_zid', LongType(), True), StructField('z_cluster', StringType(), True), StructField('z_prediction', DoubleType(), True), StructField('z_score', DoubleType(), True), StructField('z_isMatch', LongType(), True), StructField('fname', StringType(), True), StructField('lname', StringType(), True), StructField('stNo', StringType(), True), StructField('add1', StringType(), True), StructField('add2', StringType(), True), StructField('city', StringType(), True), StructField('areacode', StringType(), True), StructField('state', StringType(), True), StructField('dob', StringType(), True), StructField('ssn', StringType(), True), StructField('z_zsource', StringType(), True)])


StructField('z_isMatch', LongType(), True),

**Comment by vikasgupta78** [comment]
The issue seems to be with the way marked data has been written using zingg.writeLabelledOutputFromPandas(candidate_pairs_pd,args) in databricks notebook

**Comment by vikasgupta78** [comment]
from local machine:

>>> x = spark.read.parquet("/tmp/z_refactor/100/trainingData/marked/")
>>> x.schema                                                                    
StructType([StructField('z_zid', LongType(), True), StructField('z_cluster', StringType(), True), StructField('z_prediction', DoubleType(), True), StructField('z_score', DoubleType(), True), StructField('z_isMatch', IntegerType(), True), StructField('recId', StringType(), True), StructField('fname', StringType(), True), StructField('lname', StringType(), True), StructField('stNo', StringType(), True), StructField('add1', StringType(), True), StructField('add2', StringType(), True), StructField('city', StringType(), True), StructField('areacode', StringType(), True), StructField('state', StringType(), True), StructField('dob', StringType(), True), StructField('ssn', StringType(), True), StructField('z_zsource', StringType(), True)])

**Comment by vikasgupta78** [comment]
Only difference seems to be in z_isMatch

**Comment by vikasgupta78** [comment]
The issue has been fixed as part of PR https://github.com/zinggAI/zingg/pull/742
