### ISSUE TITLE
Can't output match result in glue notebook

### ISSUE THREAD

**Issue by TrishXie** [zinggAI/zingg#747]
**Describe the question**
Successful steps in Glue –
Able to run phases:  findTrainingData; label; train & save the model successfully.
Even able to train and build a new model from scratch.
 
 
Zingg Version – 0.4.0
 
Glue Environments – Glue 4.0 [spark 3.3.0 python 3.10] & 3.0 [spark 3.1.1 python 3.7]  
Zingg Models Tried – 100, 101, 102 & new-model-trained-using-our-data
 
Failed Zingg Phase –  match
 
Failed Code Snippet –
options = ClientOptions([ClientOptions.PHASE,"match"])
 
#Zingg execution for the given phase
zingg = ZinggWithSpark(args, options)
zingg.initAndExecute()
 
 
Error Message – No error / failure in the notebook cell. However, no output file generated.
 
Error Log  –
org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.
     at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$12(DataSource.scala:210)
     at scala.Option.getOrElse(Option.scala:121)
     at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:210)
     at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:418)
     at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
     at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
     at scala.Option.getOrElse(Option.scala:121)
     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
     at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:834)
     at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:806)
     at org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:346)
     at org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:158)
     at zingg.spark.core.util.SparkGraphUtil.buildGraph(SparkGraphUtil.java:39)
     at zingg.common.core.executor.Matcher.writeOutput(Matcher.java:252)
     at zingg.common.core.executor.Matcher.execute(Matcher.java:167)
     at zingg.common.client.Client.execute(Client.java:246)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
     at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
     at py4j.Gateway.invoke(Gateway.java:282)
     at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
     at py4j.commands.CallCommand.execute(CallCommand.java:79)
     at py4j.GatewayConnection.run(GatewayConnection.java:238)
     at java.lang.Thread.run(Thread.java:750)

**Comment by sonalgoyal** [comment]
Can you please try with spark 3.1.2 and let us know how it goes?

**Comment by sonalgoyal** [comment]
@TrishXie please let us know
