### ISSUE TITLE
Not be able to Train data in databricks

### ISSUE THREAD

**Issue by Mujammil07** [zinggAI/zingg#785]
Hi, I am trying to train data through databricks.
I followed all the steps as per the below documentation : https://github.com/zinggAI/zingg/blob/0.4.0/examples/databricks/FebrlExample.ipynb

While running this code i am getting below error : 

options = ClientOptions([ClientOptions.PHASE,"findTrainingData"])

#Zingg execution for the given phase
zingg = ZinggWithSpark(args, options)
zingg.initAndExecute()

Py4JJavaError: An error occurred while calling o586.execute.
: zingg.common.client.ZinggClientException: Boxed Error
	at zingg.common.core.executor.TrainingDataFinder.execute(TrainingDataFinder.java:139)
	at zingg.common.client.Client.execute(Client.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)

Can anyone help me to resolve this issue

**Comment by sonalgoyal** [comment]
are you running the febrl example or your own data? can you please share the logs from the driver and executor?

**Comment by sonalgoyal** [comment]
are you on spark 3.5.0 version?

**Comment by Mujammil07** [comment]
Yes

**Comment by Mujammil07** [comment]
Hi @sonalgoyal

Any updates...

**Comment by sonalgoyal** [comment]
If you are changing the name of the fields, please also change the model id
as it seems you are still referring to the old model which has the earlier
field names

Cheers,
Sonal
https://github.com/zinggAI/zingg

**Comment by sonalgoyal** [comment]
Please can you create a new issue with the exact problem, your field settings, configuration and environment along with the code you are running? It’s hard to read with multiple conversations in this thread

**Comment by Mujammil07** [comment]
Hi @sonalgoyal created new issue here https://github.com/zinggAI/zingg/issues/791

Thank you so much for your valuable advice now i am able to train data in local using docker.
