### ISSUE TITLE
Cannot read config.json in s3 when deployed to EMR

### ISSUE THREAD

**Issue by knguyen1** [zinggAI/zingg#805]
Getting file not found on EMR.

`zingg.common.client.ZinggClientException: Unable to parse the configuration at s3://my-bucket/zingg/amazon-google-config.json. The error is s3://my-bucket/zingg/amazon-google-config.json (No such file or directory)`

My file definitely exist

```
[hadoop@my-emr-machine ~]$ aws s3 ls s3://my-bucket/zingg/amazon-google-config.json
2024-03-07 18:34:24       1435 amazon-google-config.json
```

----------

Per directions at https://docs.zingg.ai/zingg/running/aws
With the command

`spark-submit --master yarn --name zingg-ai --deploy-mode cluster --class zingg.spark.client.SparkClient s3://my-bucket/zingg/zingg-0.4.0.jar --phase match --conf s3://my-bucket/zingg/amazon-google-config.json --license foo`

```
[2024-03-07 18:40:58.340]Container exited with a non-zero exit code 13. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
 INFO Client: ********************************************************
24/03/07 18:40:57 INFO Client:
24/03/07 18:40:57 INFO Client: using: Zingg v0.4.0
24/03/07 18:40:57 INFO Client:
24/03/07 18:40:57 INFO ClientOptions: --phase
24/03/07 18:40:57 INFO ClientOptions: match
24/03/07 18:40:57 INFO ClientOptions: --conf
24/03/07 18:40:57 INFO ClientOptions: s3://my-bucket/zingg/amazon-google-config.json
24/03/07 18:40:57 INFO ClientOptions: --license
24/03/07 18:40:57 INFO ClientOptions: foo
24/03/07 18:40:57 WARN ArgumentsUtil: Config Argument is s3://my-bucket/zingg/amazon-google-config.json
24/03/07 18:40:57 WARN Client: Apologies for this message. Zingg has encountered an error. Unable to parse the configuration at s3://my-bucket/zingg/amazon-google-config.json. The error is s3:/my-bucket/zingg/amazon-google-config.json (No such file or directory)
zingg.common.client.ZinggClientException: Unable to parse the configuration at s3://my-bucket/zingg/amazon-google-config.json. The error is s3:/my-bucket/zingg/amazon-google-config.json (No such file or directory)
        at zingg.common.client.ArgumentsUtil.createArgumentsFromJSON(ArgumentsUtil.java:79)
        at zingg.common.client.Client.mainMethod(Client.java:176)
        at zingg.spark.client.SparkClient.main(SparkClient.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:741)
Caused by: java.io.FileNotFoundException: s3:/my-bucket/zingg/amazon-google-config.json (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.fasterxml.jackson.core.TokenStreamFactory._fileInputStream(TokenStreamFactory.java:278)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1089)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3637)
        at zingg.common.client.ArgumentsUtil.createArgumentsFromJSON(ArgumentsUtil.java:72)
        ... 7 more
```

Also tried to define the s3 file as `s3n://`:

```
4/03/07 18:43:59 INFO ClientOptions: s3n://my-bucket/zingg/amazon-google-config.json
24/03/07 18:43:59 INFO ClientOptions: --license
24/03/07 18:43:59 INFO ClientOptions: foo
24/03/07 18:43:59 WARN ArgumentsUtil: Config Argument is s3n://my-bucket/zingg/amazon-google-config.json
24/03/07 18:43:59 WARN Client: Apologies for this message. Zingg has encountered an error. Unable to parse the configuration at s3n://my-bucket/zingg/amazon-google-config.json. The error is s3n:/my-bucket/zingg/amazon-google-config.json (No such file or directory)
zingg.common.client.ZinggClientException: Unable to parse the configuration at s3n://my-bucket/zingg/amazon-google-config.json. The error is s3n:/my-bucket/zingg/amazon-google-config.json (No such file or directory)
```

**Comment by sonalgoyal** [comment]
Can you try with https://blog.infostrux.com/identity-resolution-with-zingg-ai-snowflake-and-aws-emr-for-the-canadian-football-league-22cf0850ab53 

The config is expected locally on the driver node, the above link has instructions on creating bootstrap actions to do that. hope it helps!

**Comment by sonalgoyal** [comment]
I updated the docs using the provided article. Let me know if you still face an issue

**Comment by knguyen1** [comment]
Yes, trying it out.  Will let you know in a few days.  Thanks for helping!

**Comment by sonalgoyal** [comment]
How is it going @knguyen1 ?
